CPMAddPackage(
    NAME Luau
    GIT_TAG 0.672
    GITHUB_REPOSITORY luau-lang/luau
    OPTIONS "LUAU_BUILD_CLI OFF" "LUAU_BUILD_TESTS OFF"
)

CPMAddPackage(
    NAME libuv
    VERSION 1.50.0
    GITHUB_REPOSITORY libuv/libuv
    OPTIONS "LIBUV_BUILD_SHARED OFF" "BUILD_SHARED_LIBS OFF" "LIBUV_BUILD_TESTS OFF"
            "LIBUV_BUILD_BENCH OFF"
)
